/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rate.limiter

class BucketTokenRateLimiterTest {
//    @Test
//    fun testAppHasAGreeting() = runBlocking {
//        val classUnderTest = HostsLimiter(10, 100)
//        for(i in 1..80) {
//            delay(5)
//            println(classUnderTest.consume())
//        }
//    }
}
